version: '3.8'
services:

  dev-db:

    image: postgres:16.0

    ports:

      - 5434:5432

    restart: always

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: 123

      POSTGRES_DB: nest

    networks:

      - devnextx

  test-db:

    image: postgres:16.0

    ports:

      - 5435:5432

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: 123

      POSTGRES_DB: nest

    networks:

      - devnextx

networks:

  devnextx: